#!/bin/zsh
#echo "Experiment: sum of all digits using function"
function sumdigits()
{
 num=$1
 sum=0
 while [ $num -gt 0 ]
 do
      digit=`expr $num % 10`
      sum=`expr $sum + $digit`
      num=`expr $num / 10`
 done 
 echo "$sum"
}
echo "Enter Number:"
read a
sum=$(sumdigits $a)
echo "The sum of digits is: $sum”
